// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3v9gqOz4OVp3Z7PoWsrEobE4qfY9aDs',
    appId: '1:890085679645:web:ac4c30128d555d2e505cf4',
    messagingSenderId: '890085679645',
    projectId: 'my-clone-instagram-flutter',
    authDomain: 'my-clone-instagram-flutter.firebaseapp.com',
    storageBucket: 'my-clone-instagram-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCho-tDUY09SmqN85kVh1-W9M4lLrp4B2I',
    appId: '1:890085679645:android:5da867c6a8ed7da0505cf4',
    messagingSenderId: '890085679645',
    projectId: 'my-clone-instagram-flutter',
    storageBucket: 'my-clone-instagram-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnshCZacNGSfW8ffWPbvgUzAJqmlV844g',
    appId: '1:890085679645:ios:58c846c574d87b6a505cf4',
    messagingSenderId: '890085679645',
    projectId: 'my-clone-instagram-flutter',
    storageBucket: 'my-clone-instagram-flutter.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnshCZacNGSfW8ffWPbvgUzAJqmlV844g',
    appId: '1:890085679645:ios:6151eacc3ade9f5d505cf4',
    messagingSenderId: '890085679645',
    projectId: 'my-clone-instagram-flutter',
    storageBucket: 'my-clone-instagram-flutter.appspot.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
